#!/bin/perl
use Getopt::Long; #S'emprara la funció Getopt per recuperar els arguments de l'script
$Usage="\n Ajudame\n";

@translate;
$transl_table;

sub recupera_ARGV{
  $SIG{__WARN__}= sub {die $Usage;};
  GetOptions(
    'transl_table=i' => \$transl_table,
    'translate=s' => \@translate
  );
  print "Es traduirà segons la taula $transl_table \n";
}

&recupera_ARGV;

print "@translate\n";
print "paco\n"
